"""initial_schema

Revision ID: 79050fa926a5
Revises: 
Create Date: 2026-05-10 10:49:06.354239
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79050fa926a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True, comment='deprecated: kept temporarily for backward compatibility'),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True, comment='True if record is from seed data (test), False if from external sync (real)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', name='uq_external_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_date_category_status', ['date', 'category', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)

    op.create_table('sync_state',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_external_id'))
        batch_op.drop_index('ix_products_date_category_status')

    op.drop_table('products')
    # ### end Alembic commands ###